### ISSUE TITLE
Why I would like to change the current logging model

### ISSUE THREAD

**Issue by gabriel10619** [nidhaloff/b-rabbit#10]
The following code snippet is an example of how adding the helpers file to your local directory can only save you for so long. In this example, the helpers file had been copied to every directory containing code in which b-rabbit was being imported, but the code is still unable to function when using a python dependency manager (At least it doesn't work when using poetry). Hopefully this will be fixed by the end of the week!

../../../.cache/pypoetry/virtualenvs/sectry-8eJmSxWQ-py3.7/lib/python3.7/site-packages/b_rabbit/__init__.py:3: in <module>
    from .b_rabbit import BRabbit
../../../.cache/pypoetry/virtualenvs/sectry-8eJmSxWQ-py3.7/lib/python3.7/site-packages/b_rabbit/b_rabbit.py:8: in <module>
    from helpers.logs import create_logger
E   ModuleNotFoundError: No module named 'helpers'
Error: Process completed with exit code 4.

**Comment by nidhaloff** [comment]
@gabriel10619 Hi thanks for your work. Did the last PR fix this problem already? if yes then maybe we can close this issue

**Comment by gabriel10619** [comment]
@nidhaloff i will be away from my work until next week. 

I will let you know the results when I am able to test b-rabbit with poetry.
