### ISSUE TITLE
helpers.logs doesnt exist

### ISSUE THREAD

**Issue by OfekShochat** [nidhaloff/b-rabbit#4]
b_rabbit version: latest
Python version: 3.8.6
Operating System: macos

### Description

when importing b-rabbit it looks for helpers.logs which doesnt exist.
(on github it does, so I think you should use .helpers.logs or something)

### What I Did

```
Traceback (most recent call last):
  File "serve.py", line 1, in <module>
    from b_rabbit import BRabbit
  File "/Users/oshochat/Library/Python/3.8/lib/python/site-packages/b_rabbit/__init__.py", line 3, in <module>
    from .b_rabbit import BRabbit
  File "/Users/oshochat/Library/Python/3.8/lib/python/site-packages/b_rabbit/b_rabbit.py", line 8, in <module>
    from helpers.logs import create_logger
ModuleNotFoundError: No module named 'helpers.logs'
```

**Comment by OfekShochat** [comment]
this doesnt work also on windows and python 3.8

**Comment by OfekShochat** [comment]
just need to copy helpers folder into the directory

**Comment by blitz-de** [comment]
Why was this closed. The problem still persists. I am getting also " ModuleNotFoundError: No module named 'helpers.logs'"

**Comment by OfekShochat** [comment]
if I remember correctly, I moved the folder into the current one (where your project is in). but this was so long ago...
